### ISSUE TITLE
[Enhancement] Support BlazorWebView with GTK

### ISSUE THREAD

**Issue by 3D-aero-sbahr** [lytico/maui#9]
## Summary
Photino (https://www.tryphotino.io/), the successor of Steve Sandersons WebWindow,  has stopped the support for Blazor, because they think MAUI will bring better support. But MAUI does not support Linux, so there is no support for Blazor Desktop on Linux. If this port for Linux would support Blazor, this gap could be closed and the .net linux community would have a great modern UI framework to develop native cross-plattform apps.

**Comment by CommonLoon102** [comment]
Shouldn't be a huge thing as we already have similar sample implementations:
https://github.com/dotnet/maui/blob/main/src/BlazorWebView/src/Maui/Android/WebKitWebViewClient.cs

If the WebView component (WebKit based) really already works from GtkSharp, then it should be straightforward.
https://github.com/lytico/maui/issues/1

**Comment by lytico** [comment]
lets discuss that here: https://github.com/jsuarezruiz/maui-linux/issues/28
